### ISSUE TITLE
Page discovery

### ISSUE THREAD

**Issue by jaredsmithse** [jarrydlee/fuzzer#2]
The fuzzer must crawl and guess pages. This has two parts:

- [ ] **Link discovery** The fuzzer should keep a list of URLs that it can reach from the initial given page. Do not follow any links off-site in your crawl.
- [ ] **Page Guessing.** The fuzzer should use a common word list to discover potentially unlinked pages. Be sure to attempt relevant url extensions, such as ".php" or ".jsp"

**Comment by jarrydlee** [comment]
You might want to use the parse branch that I'm going to push soon so that you don't crawl offsite links

**Comment by jaredsmithse** [comment]
Will do, what are we waiting on to merge it into `master`?

**Comment by jarrydlee** [comment]
It is already merged

**Comment by jaredsmithse** [comment]
Alright, working on this late tonight then.
